- name: variables from prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: enter your username
      private: false
    - name: PASSWORD
      prompt: enter your password
      private: true
  tasks:
    - name: Variables from prompt
      ansible.builtin.debug:
        msg: "The {{USERNAME}} you entered and password {{PASSWORD}}"

