- name: mangodb installing
  hosts: localhost
  tasks:
  - name: Copying Mangodb repo
    ansible.builtin.copy:
      src: mango.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: Installing mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: present
  - name: Starting mongodb service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: Replacing the String
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1 
      replace: 0.0.0.0
  - name: restarting the asterisk
    ansible.builtin.service: 
      name: mongod
      state: restarted
